# coding: utf-8

"""
    BlockMarkets Cryptocurrency API

    The BlockMarkets API provides real-time and historical market data on cryptocurrencies from the world's leading crypto exchanges. Sign up for a free, unlimited API key at [BlockMarkets Cryptocurrency API](https://www.blockmarkets.io/cryptocurrency-api).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import blockmarkets
from blockmarkets.models.empty import Empty  # noqa: E501
from blockmarkets.rest import ApiException


class TestEmpty(unittest.TestCase):
    """Empty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmpty(self):
        """Test Empty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = blockmarkets.models.empty.Empty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
