# coding: utf-8

# flake8: noqa

"""
    BlockMarkets Cryptocurrency API

    The BlockMarkets API provides real-time and historical market data on cryptocurrencies from the world's leading crypto exchanges. Sign up for a free, unlimited API key at [BlockMarkets Cryptocurrency API](https://www.blockmarkets.io/cryptocurrency-api).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from blockmarkets.api.default_api import DefaultApi

# import ApiClient
from blockmarkets.api_client import ApiClient
from blockmarkets.configuration import Configuration
# import models into sdk package
from blockmarkets.models.empty import Empty
